### ISSUE TITLE
Cannot get ssh keys

### ISSUE THREAD

**Issue by benzid-wael** [cloud66/habitus#40]
Trying to run habitus even with the provided example, I get:

> security git:(master) ✗ habitus_linux_amd64 --host=unix:///var/run/docker.sock --binding=127.0.0.1 --build host=127.0.0.1
> 2016/10/24 16:14:55 ▶ Using '/home/wael/workspace/habitus/examples/security/build.yml' as build file 
> 2016/10/24 16:14:55 ▶ Collecting artifact information 
> 2016/10/24 16:14:55 ▶ Building 1 steps 
> 2016/10/24 16:14:55 ▶ Step 0 - builder: builder 
> 2016/10/24 16:14:55 ▶ Parallel build for builder 
> 2016/10/24 16:14:55 ▶ Building builder 
> 2016/10/24 16:14:55 ▶ Parsing and converting 'Dockerfile' 
> 2016/10/24 16:14:55 ▶ Starting API on 8080 
> 2016/10/24 16:14:55 ▶ Writing the new Dockerfile into Dockerfile.generated 
> 2016/10/24 16:14:55 ▶ Building the builder image from Dockerfile.generated 
> Step 1 : FROM ubuntu
>  ---> f753707788c5
> Step 2 : RUN apt-get update && apt-get install -y wget openssh-client
>  ---> Using cache
>  ---> f149286ec705
> Step 3 : RUN mkdir ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
>  ---> Using cache
>  ---> d093edca0423
> Step 4 : ARG host
>  ---> Using cache
>  ---> e744a38e08e2
> Step 5 : ENV PRIVATE_KEY /root/.ssh/id_rsa
>  ---> Using cache
>  ---> 1a1212d088d7
> Step 6 : RUN wget -O $PRIVATE_KEY http://$host:8080/v1/secrets/file/id_rsa && chmod 0600 $PRIVATE_KEY && ssh -T git@github.com && rm $PRIVATE_KEY
>  ---> Running in 0bd430f3b4ef
> --2016-10-24 14:14:55--  http://127.0.0.1:8080/v1/secrets/file/id_rsa
> Connecting to 127.0.0.1:8080... failed: Connection refused.
> 2016/10/24 16:14:56 ▶ Build for step builder failed due to The command '/bin/sh -c wget -O $PRIVATE_KEY http://$host:8080/v1/secrets/file/id_rsa && chmod 0600 $PRIVATE_KEY && ssh -T git@github.com && rm $PRIVATE_KEY' returned a non-zero code: 4

**Command**
 $ habitus_linux_amd64 --host=unix:///var/run/docker.sock --binding=127.0.0.1 --build host=127.0.0.1

**Environment**:
- Ubuntu 16.04 and Docker 1.12.1

**Comment by mirestrepo** [comment]
@benzid-wael Did you get past this error? I have the same problem

**Comment by mirestrepo** [comment]
Got the solution in my case from this thread #14 

```
#check active private ip, could be any enX

ipconfig getifaddr en0

sudo habitus --build host=$(ipconfig getifaddr en0) --host unix:///var/run/docker.sock --binding=0.0.0.0
```

Then the Docker file can look like the [example](https://github.com/cloud66/habitus/blob/master/examples/security/Dockerfile)

**Comment by Apokly** [comment]
Had to do almost same for linux :

`habitus --host=unix:///var/run/docker.sock --binding=0.0.0.0 --build host=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')`

**Comment by cnjr2** [comment]
In the `Habitus IP address` section of the [main site](http://www.habitus.io/) the following is mentioned:

>Finding the correct IP address to server Habitus API (and secrets) on can be tricky. You don't want to bind it to 0.0.0.0 since it will make Habitus and your secrets available to your entire local network (and possibly the internet if you're running a tunnel) during the build time.

Is it still fine to use the `--binding=0.0.0.0` option?

**Comment by Apokly** [comment]
Hi @cnjr2 ,

Definitely not ! All your local network will access your file. I did it just to test.

**Comment by cnjr2** [comment]
Hey @Apokly, thanks for your reply. I have also been able to do builds when using the `--binding=0.0.0.0`, but not with other IPs, such as the default mentioned. Do you know how to find out which one is usable and safe?

**Comment by Apokly** [comment]
No, I didn't really spend a lot of time using Habitus, since I wondered how to use it in an external context (with https://zeit.co/now for example). I tried with my own local IP and docker's one (Docker network interface, called docker0 on linux). But if you find the solution, I'll really appreciate an answer.

**Comment by cnjr2** [comment]
I have settled for this for now:
```
host=$(ipconfig getifaddr en0)
sudo habitus --build host=$host --host unix:///var/run/docker.sock --binding=$host
```

**Comment by kamerblauwlicht** [comment]
**To clarify this issue.**

Habitus is an application which doesn't run in your docker network! 
If you use want to expose your secrets to your builds you have to tell Habitus on which IP address it needs to bind and expose the secrets. Use the `--binding` to tell Habitus which IP address it has to bind to. 

The next step is to tell the build process where Habitus is exposing his secrets. Because every build process is isolated and has his own network, you can't bind to localhost or something. You need the real IP of the exposed secrets. The easiest way is to use build environments with the `--build` switch.

`$habitus --bind [ip_to_bind_to] --build HABITUS_SECRET_SERVER=[ip_to_bind_to]` 

In you Dockerfile you can use the Docker build argument.

```
 ARG HABITUS_SECRET_SERVER
 RUN wget -O ~/.ssh/id_rsa http://$HABITUS_SECRET_SERVER:8080/v1/secrets/file/id_rsa
```

**Comment by Apokly** [comment]
> You need the real IP of the exposed secrets

So I need to have a server that expose, for example, my private SSH key and so habitus will `wget` it every time I deploy my Dockerfile ? What's goal ? What about security ?

I won't expose my private SSH key on a webserver, even with the default 80 port, so if it's the solution i will definitely **not** use Habitus.

**Comment by kamerblauwlicht** [comment]
@Apokly your end goal is to create a Docker image without any trace of your secrets and deploy this Docker image to production. You don't want your private keys on your webserver of course. And binding Habitus to an IP address can be a private one of course which is not connected to the Internet of course. 

A lot of Habitus users are running Habitus in their own CI/CD solution using the keys in a secure environment and build the Docker image and push the Docker images (without secrets) to a registry and deploy it on the Docker cluster.

P.S. I removed real because this was confusing.

**Comment by Apokly** [comment]
Understood ! Thank you for quick and useful answers. I'm still convinced that it's a little bit insecure since you have to expose permanently you secret keys on a webserver (even if not connected to internet), but I understand the meaning.

**Comment by kamerblauwlicht** [comment]
@Apokly no problem.  Habitus is only exposing the secrets uring the build, when Habitus is done there is not secret service of course bind to an IP address.
