### ISSUE TITLE
Container may not have `stat`

### ISSUE THREAD

**Issue by josephschorr** [cloud66/habitus#8]
Currently, the `stat command is used before extracting files from the container (see: https://github.com/cloud66/habitus/blob/master/build/builder.go#L340). Certain containers (such as`scratch`) will not contain this method and will fail to extract the file. In those cases it may make sense to fallback to not copying over the file permissions.

**Comment by jzelinskie** [comment]
There is another option rather than trying to exec stat on the container. You could also just copy/stat it from the host where docker is mounting the volumes. This obviously doesn't work if you aren't on the same machine as the docker daemon and would likely require root.

**Comment by michaelhue** [comment]
I ran into some problems trying to use alpine based images in Habitus. The image didn't have bash installed but that could be fixed by adding `apk add bash` to the Dockerfile. However the `stat` command seems to work differently on alpine; it throws an error because the "format" option is not recognized.

This is when I gave up on using the alpine image (19 MB) and switched to an Ubuntu based image (258 MB) instead.

I think the build pipeline should be a bit more resilient to different OS in images. Maybe the [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/) command could be used to get the artifacts out instead? This should work with any docker image.

**Comment by kamerblauwlicht** [comment]
hi @michaelhue.  thanks for the feedback. the stats command is to get the permission right. I assigned to a new milestone to dive deeper in this matter

**Comment by michaelhue** [comment]
Hey @kamerblauwlicht, thanks for the response!

Regarding permissions with `docker cp`:

> The cp command behaves like the Unix cp -a command in that directories are copied recursively with permissions preserved if possible. Ownership is set to the user and primary group at the destination. For example, files copied to a container are created with UID:GID of the root user. Files copied to the local machine are created with the UID:GID of the user which invoked the docker cp command. If you specify the -L option, docker cp follows any symbolic link in the SRC_PATH. docker cp does not create parent directories for DEST_PATH if they do not exist.

Sounds reasonable but I'm not sure if this is the behavior you need.

**Comment by kamerblauwlicht** [comment]
@michaelhue thanks. will work on this for the next release. let me check if I can make this part of Habitus more resilient.

**Comment by johnphho** [comment]
I added coreutils to alpine and it worked for me.

**Comment by kamerblauwlicht** [comment]
stat can cause problems using stat, breaking build. looking for an alternative.

![screen shot 2017-03-10 at 10 24 37](https://cloud.githubusercontent.com/assets/531668/23789727/5dc6c722-057c-11e7-940f-c2470ac06ae8.png)

**Comment by kamerblauwlicht** [comment]
https://docs.docker.com/engine/reference/commandline/cp/

**Comment by kamerblauwlicht** [comment]
we are using docker cp in the background, don't need stat. removing it. docker cp trying to keep the   premissions
